# Generated by Django 3.2.9 on 2022-05-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0002_mynote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynote',
            name='files',
        ),
        migrations.AddField(
            model_name='mynote',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='files', to='mynotes.Notes'),
        ),
    ]
