# Generated by Django 3.2.9 on 2022-05-31 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0003_auto_20220531_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
