# Generated by Django 3.2.9 on 2022-05-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0004_alter_mynote_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mynote',
        ),
    ]
