# Generated by Django 3.2.9 on 2022-06-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0005_delete_mynote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.CharField(max_length=10000),
        ),
    ]
