# Generated by Django 3.2.9 on 2022-06-08 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0007_alter_notes_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Wishlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
