# Generated by Django 3.2.9 on 2022-06-06 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0007_alter_notes_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fnote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mynotes.notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mynotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
