# Generated by Django 3.2.9 on 2022-06-06 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0008_fnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnote',
            name='files',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mynotes.notes'),
        ),
    ]
