# Generated by Django 3.2.9 on 2022-06-08 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0008_auto_20220608_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user',
            new_name='owner',
        ),
    ]
