# Generated by Django 3.2.9 on 2022-06-06 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0009_alter_fnote_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fnote',
            name='files',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='mynotes.notes'),
        ),
    ]
