# Generated by Django 3.2.9 on 2022-06-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0010_fpass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Wishlist',
            new_name='passwor',
        ),
    ]
